services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gas
      POSTGRES_PASSWORD: gas
      POSTGRES_DB: shop
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "5050:5050"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: gas
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"